# Generated by Django 5.1.7 on 2026-05-19 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0007_rename_tecnologias_usadas_jobpost_area_desenvolvimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='empresa',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='source',
            field=models.CharField(default='manual', max_length=50),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
